### ISSUE TITLE
能否提供下现在黑苹果的工作情况以及bios设置

### ISSUE THREAD

**Issue by wintry** [RainshawGao/Hackintosh#1]
谢谢

**Comment by Rainshaw** [comment]
你都需要哪些信息？
目前来看，我的日常使用是完全没问题的。
我没有关注是否支持硬解，因为我没有那么多4k资源，1080P就算不硬解我CPU也完全扛得住，你可以自行测试。
关于BIOS的设置，我是按照 https://blog.xjn819.com/?p=543 博客中的通用bios设置改的，其他部分没有改动。
