### ISSUE TITLE
请问是否碰到关机重启的问题

### ISSUE THREAD

**Issue by nylqd** [RainshawGao/Hackintosh#2]
参照 https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html

FixShutdown-USB-SSDT.dsl 似乎并不奏效？

**Comment by Rainshaw** [comment]
> 参照 https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html
> 
> FixShutdown-USB-SSDT.dsl 似乎并不奏效？

我没有遇到过。
你和我是同一个主板？我现在是最新的BIOS，除了超频外其余bios设置均按照readme改的。

**Comment by nylqd** [comment]
> > 参照 [dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html](https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html)
> > FixShutdown-USB-SSDT.dsl 似乎并不奏效？
> 
> 我没有遇到过。
> 你和我是同一个主板？我现在是最新的 BIOS，除了超频外其余 bios 设置均按照 readme 改的。

是的都是M10h，区别在于我没有用A卡了，记得之前用clover也有过fixShutdown，这个周末折腾到opencore发现就这个关机重启比较难受，其他的都挺好，我去更新下bios试试

**Comment by nylqd** [comment]
升级最新bios之后问题解决👏🏻
